spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xcytest?serverTimezone=UTC
    username: root
    password: root
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
    static-path-pattern: /**
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xcy.pojo
  configuration-properties:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.xcy.dao: DEBUG
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
server:
  port: 8099
  servlet:
    context-path: /